#!/usr/bin/env python
# -*- coding: utf-8 -*-

from distutils.core import setup

setup(
    name='h5logiqa',
    version='1.0',
    description='h5logiqa is a module to retrieve Hi-C data from HDF5 files generated by LOGIQA',
    author='Matthias Blum',
    author_email='mat.blum@gmail.com',
    url='https://github.com/matthiasblum/h5logiqa',
    py_modules=['h5logiqa'],
    zip_safe=False,
)